workflows:
  # PR 검증 워크플로우 (CI 전용)
  ci-workflow:
    name: CI - PR Validation
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/Library/Caches/CocoaPods
        - $HOME/Library/Android/sdk

    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: false
        - pattern: main
          include: true
          source: false
      cancel_previous_builds: true

    scripts:
      - name: Create temporary .env file for CI
        script: |
          echo "NAVER_MAP_CLIENT_ID=dummy_client_id_for_ci" > .env
          
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Generate code with build_runner
        script: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Run unit tests
        script: |
          flutter test
          
      # - name: Build Android debug APK (optional)
      #   script: |
      #     flutter build apk --debug
      #   ignore_failure: true
          
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log

# CD파이프라인은 추후 추가
